_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/Path/to/Base/Pretrain/Weight"
  MASK_ON: False
  BACKBONE:
    FREEZE: False
  RESNETS:
    DEPTH: 101
  RPN:
    FREEZE: False
  ROI_HEADS:
    NUM_CLASSES: 20
    FREEZE_FEAT: True
    CLS_DROPOUT: True
DATASETS:
  TRAIN: ("coco14_trainval_novel_10shot_seed0", )
  TEST: ('coco14_test_novel',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (800,)
  MAX_ITER: 1000
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 0
OUTPUT_DIR: "checkpoints/coco/gdl/fsod_r101_ft"