_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/Path/to/Base/Pretrain/Weight"
  MASK_ON: False
  BACKBONE:
    FREEZE: False
  RESNETS:
    DEPTH: 101
  RPN:
    FREEZE: False
  ROI_HEADS:
    NUM_CLASSES: 5
    FREEZE_FEAT: True
    CLS_DROPOUT: True
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ("voc_2007_trainval_novel1_1shot_seed0", )
  TEST: ("voc_2007_test_novel1",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (640, )
  MAX_ITER: 800
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 0
OUTPUT_DIR: "checkpoints/voc/origin/fsod_r101_ft"
